// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// rcpparma_L2stat
double rcpparma_L2stat(const arma::mat& V, const arma::uvec& sample_num, int k, int p, int n);
RcppExport SEXP ECFsup_rcpparma_L2stat(SEXP VSEXP, SEXP sample_numSEXP, SEXP kSEXP, SEXP pSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type sample_num(sample_numSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpparma_L2stat(V, sample_num, k, p, n));
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_fKSCovL2
double rcpparma_fKSCovL2(const arma::mat& data, const arma::uvec& sample_num, int k, int p, int n, int Nsim);
RcppExport SEXP ECFsup_rcpparma_fKSCovL2(SEXP dataSEXP, SEXP sample_numSEXP, SEXP kSEXP, SEXP pSEXP, SEXP nSEXP, SEXP NsimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type sample_num(sample_numSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type Nsim(NsimSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpparma_fKSCovL2(data, sample_num, k, p, n, Nsim));
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_maxstat
double rcpparma_maxstat(const arma::mat& V, const arma::uvec& sample_num, int k, int p, int n);
RcppExport SEXP ECFsup_rcpparma_maxstat(SEXP VSEXP, SEXP sample_numSEXP, SEXP kSEXP, SEXP pSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type sample_num(sample_numSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpparma_maxstat(V, sample_num, k, p, n));
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_fKSCovsup
double rcpparma_fKSCovsup(const arma::mat& data, const arma::uvec& sample_num, int k, int p, int n, int Nsim);
RcppExport SEXP ECFsup_rcpparma_fKSCovsup(SEXP dataSEXP, SEXP sample_numSEXP, SEXP kSEXP, SEXP pSEXP, SEXP nSEXP, SEXP NsimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type sample_num(sample_numSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type Nsim(NsimSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpparma_fKSCovsup(data, sample_num, k, p, n, Nsim));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"ECFsup_rcpparma_L2stat", (DL_FUNC) &ECFsup_rcpparma_L2stat, 5},
    {"ECFsup_rcpparma_fKSCovL2", (DL_FUNC) &ECFsup_rcpparma_fKSCovL2, 6},
    {"ECFsup_rcpparma_maxstat", (DL_FUNC) &ECFsup_rcpparma_maxstat, 5},
    {"ECFsup_rcpparma_fKSCovsup", (DL_FUNC) &ECFsup_rcpparma_fKSCovsup, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_ECFsup(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
