# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_L2stat <- function(V, sample_num, k, p, n) {
    .Call(ECFsup_rcpparma_L2stat, V, sample_num, k, p, n)
}

rcpparma_fKSCovL2 <- function(data, sample_num, k, p, n, Nsim = 1000L) {
    .Call(ECFsup_rcpparma_fKSCovL2, data, sample_num, k, p, n, Nsim)
}

rcpparma_maxstat <- function(V, sample_num, k, p, n) {
    .Call(ECFsup_rcpparma_maxstat, V, sample_num, k, p, n)
}

rcpparma_fKSCovsup <- function(data, sample_num, k, p, n, Nsim = 1000L) {
    .Call(ECFsup_rcpparma_fKSCovsup, data, sample_num, k, p, n, Nsim)
}

